
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 574291
	#The name of the modpack
	modpackName = "Prominence II [FORGE] Void's Invasion"
	#The version of the modpack
	modpackVersion = "v1.3.6"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

